### ISSUE TITLE
panic (trackercounters flatten assertion error) when running e2e tests for pidwatcher with multiple trackers

### ISSUE THREAD

**Issue by yanjing1104** [intel/memtierd#4]
When running e2e tests for pidwatcher with multiple trackers ( refer to: https://github.com/intel/memtierd/pull/5/), the following panic err will be raised.

For all the pidwatchers (PidWatcherProc, PidWatcherCgroups, pidlist), this issue can be reproduced. The following err is for when pidwatcher is pidlist.

DEBUG: memtier TrackerIdlePage: AddPids([10412 10427 10442])
DEBUG: memtier TrackerSoftDirty: online
DEBUG: memtier TrackerIdlePage: online
DEBUG: memtier TrackerSoftDirty: AddPids([10412 10427 10442])
memtierd> DEBUG: memtier Mover: online
DEBUG: memtier PolicyAge: online
DEBUG: memtier PolicyAge: offline
panic: trackercounters flatten assertion error: not sorted by addresses

goroutine 9 [running]:
github.com/intel/memtierd/pkg/memtier.(*TrackerCounters).Flattened(0xc000065c50, 0x0, 0x0)
	/root/go/src/github.com/intel/memtierd/pkg/memtier/tracker.go:254 +0x1067
github.com/intel/memtierd/pkg/memtier.(*TrackerMulti).GetCounters(0xc000016200?)
	/root/go/src/github.com/intel/memtierd/pkg/memtier/tracker_multi.go:108 +0x14d
github.com/intel/memtierd/pkg/memtier.(*PolicyAge).loop(0xc0000164c0)
	/root/go/src/github.com/intel/memtierd/pkg/memtier/policy_age.go:459 +0x23a
created by github.com/intel/memtierd/pkg/memtier.(*PolicyAge).Start
	/root/go/src/github.com/intel/memtierd/pkg/memtier/policy_age.go:307 +0x12a
2023/07/07 12:47:00 socat[10498] E write(1, 0x564815a6d000, 53): Broken pipe
2023/07/07 12:47:03 socat[10512] E write(1, 0x564815a6d000, 53): Broken pipe
2023/07/07 12:47:05 socat[10526] E write(1, 0x564815a6d000, 53): Broken pipe
2023/07/07 12:47:07 socat[10540] E write(1, 0x564815a6d000, 53): Broken pipe
2023/07/07 12:47:09 socat[10554] E write(1, 0x564815a6d000, 53): Broken pipe
2023/07/07 12:47:11 socat[10568] E write(1, 0x564815a6d000, 53): Broken pipe

**Comment by yanjing1104** [comment]
After re-testing it, it seems that I could not always reproduce it, will keep checking.
https://github.com/intel/memtierd/pull/5#issue-1778685207
